### PR TITLE
Fix Certificate Validation Using AIA

### PR DESCRIPTION
**Pull request by WillKoehrsen**
## Summary

- Fixes certificate validation for servers lacking intermediate certificates by downloading them to a temporary file using Authority Information Access (AIA)
- Allows us to use SSL/TLS with requests even for servers lacking a complete certificate chain

### Details

- AIA: https://akamath32.medium.com/certificate-authority-information-access-aia-7bc56f7257fc
- aia library: https://github.com/danilobellini/aia/tree/master
- AIA lacking in Python: https://github.com/python/cpython/issues/62817
- SSL Labs report showing incomplete certificate chain for www.ieso.ca: https://www.ssllabs.com/ssltest/analyze.html?d=www.ieso.ca&latest

### CODE REVIEW

**Review by kmax12 — APPROVED** [review]
I haven't run the code, but I'm good with this solution

**Comment by WillKoehrsen** [comment]
This isn't working in GitHub actions (the tests) so I doubt it'll work in our cloud deployment. Working on a fix.

**Comment by WillKoehrsen** [comment]
I can't get this to work in GitHub actions. The error is:

```
Root in AIA but not in trusted list
```

which wasn't solved by installing `openssl` and `ca-certificates`.

**Comment by WillKoehrsen** [comment]
Since this doesn't work in GitHub actions, closing in favor of #495.

**Pull request closed without merging**
