### PR TITLE
Fix Tests August 2024

### PR DESCRIPTION
**Pull request by WillKoehrsen**
- Attempts to fix the failing tests

### CODE REVIEW

**Comment by kmax12** [comment]
@WillKoehrsen im good to merge these in when you are

**Comment by WillKoehrsen** [comment]
I think we might be getting rate-limited by the ERCOT API because the tests for Python 3.10 and 3.11 run at the same time with the same creds.

**Comment by WillKoehrsen** [comment]
> I think we might be getting rate-limited by the ERCOT API because the tests for Python 3.10 and 3.11 run at the same time with the same creds.

This doesn't seem to be the case but the ERCOT API tests are failing.

**Review by Kladar — APPROVED** [review]
Thanks for fixing! Would love to get to a point where we basically just rely on good, comprehensive testing such that PRs that pass everything can be merged with as little human intervention as possible.

**Pull request merged**
