### PR TITLE
Implement another approach to ERCOT API bulk document downloading

### PR DESCRIPTION
**Pull request by kmax12**
Took another stab at implementing the bulk data download.

Per our discussion this morning, I wanted to separate the downloading of the data from the processing of it. In the future, it should be a little bit easier to tease these piece apart. for example, if we wanted to write these data to S3 before processing it. 

In my opinion it also made this code more maintainable since the parsing logic is now the same regardless of it we are bulk downloading or individually downloading. 

My biggest concern is this approach takes more memory since we are storing both file bytes and parsed dataframes in memory. Before, we only stored the parsed dataframe. I'm not sure this matters, but it might on render where we try to run jobs on as small boxes as possible.

### CODE REVIEW

**Comment by Kladar** [comment]
I'm getting a test failure on the fallback day stemming from a docId order issue

To reproduce:
```
df = ercotapi.get_indicative_lmp_by_settlement_point(
    date="2024-11-03 00:00:00",
    end="2024-11-03 04:00:00",
)
```

CleanShot 2024-12-17 at 07 53 54@2x

**Comment by WillKoehrsen** [comment]
> @WillKoehrsen do you want to test this branch with the wind/solar backfill you are doing?

Yep, it works running locally. As you mentioned, we might have memory issues on Render but it's good to have this option.

**Review by Kladar — APPROVED** [review]
Nice, working for me now

**Comment by kmax12** [comment]
I feel good about merging this to your branch, but I still want to work through the failing ercot tests. at least one is preexisting, but not sure about all of them

**Pull request merged**
